DEFINED_ATTR_NAMES_EF={
    "Demographic": "Demographic",
    "Yield Per Unit": "zReserveAQ",
    "Label Code": "Dom/Imp",
    "Department": "Department",
    "Color Desc": "Color Description",
    "Vendor Ref #": "zReserveAL",
    "NRF Color Code": "Color# NRF",
    "Season Code": "zReserveAI",
    "Company": "Company",
    "Style #": "EF Style",
    "Age Group": "zReserveBI",
    "Short Color Desc": "zReserveAU",
    "Region": "ORG Code",
    "Product Category Code": "zReserveV",
    "Pricing Zone": "Pricing Zone",
    "Style Desc": "Description",
    "Fabric Category": "Agent",
    "Owned Cost": "zReserveAG",
    "Start Ship Date": "zReserveAY",
    "Group Code": "zReserveX",
    "Change Date": "zReserveC",
    "Low Retail": "Low Retail",
    "Style Fabric": "Factory",
    "MSRP": "Retail Price",
    "Material Type": "zReserveBN",
    "STD Cost": "Estimated Cost",
    "Color Info": "Main Sew venue",
    "Vendor Color Family": "zReserveAT",
    "Product Category": "Story",
    "Door": "Customer",
    "Color Indicator": "COO",
    "Season": "Fashion Season",
    "Multi Channel Indicator": "zReserveCA",
    "Replenishment Indicator": "zReserveBQ",
    "Country": "Currency",
    "Discontinue Date": "zReserveD",
    "Class": "Style Classification",
    "Product Stop Date": "zReserveBO",
    "Term": "zReserveN",
    "Budget": "Budget",
    "UPC": "UPC",
    "WHSL": "Wholesale Price",
    "Dimension": "Dimension",
    "Fit Type": "zReserveBK",
    "Location Attr4": "Location Attr4",
    "Delivery Date": "zReserveP",
    "Location Attr6": "Location Attr6",
    "Location Attr0": "Location Attr0",
    "Location Attr1": "Location Attr1",
    "Location Attr2": "Location Attr2",
    "Location Attr3": "Location Attr3",
    "Sell In/Sell Thru": "Sell In/Sell Thru",
    "Retailer Color Code": "zReserve01",
    "Category": "Material Parent Group",
    "Group": "Main Material",
    "Style Name": "zReserveE",
    "STOO": "STOO",
    "Additional Info": "zReserveQ",
    "Owned Retail": "zReserveAH",
    "Size Name": "Size",
    "Merch Plan": "Merch Plan",
    "Color Code": "Color Code",
    "Hang/Fold": "Eco Tier",
    "Gear Line": "zReserveBJ",
    "Div Dept Code": "zReserveAJ",
    "Collar": "zReserveAR",
    "Product Team": "L/S Page Title",
    "Exclusive": "zReserveAX",
    "Production Type": "Material Class",
    "Country Code": "zReserveBM",
    "Summary": "Summary",
    "Store Type Code": "Store Type Code",
    "Stock Category": "Stock Category",
    "PO Definition": "PO Definition",
    "Article #": "zReserveBX",
    "Low Cost": "Low Cost",
    "Vendor Color Code": "zReserveAP",
    "Color Priority": "Color Priority",
    "Fiber Content": "Main Material Content",
    "Location Attr5": "Location Attr5",
    "Ethnicity": "Ethnicity",
    "Range Code": "zReserveAK",
    "Style Type": "zReserveBL",
    "Factory": "zReserveCH",
    "Style Minimum 4": "Style Minimum 4",
    "Style Minimum 1": "Style Minimum 1",
    "Style Minimum 2": "Style Minimum 2",
    "Style Minimum 3": "Style Minimum 3",
    "Division": "Division",
    "Size Code": "Size Code",
    "Department Type": "Department Type",
    "Store Category": "Store Category",
    "Pattern #": "zReserveAV",
    "Key Item Indicator": "zReserveBZ",
    "Corporate Division": "Corporate Division",
    "Fabrication": "Fabrication",
    "Climate": "Climate",
    "Color Category": "Customer Account Code",
    "Sleeve": "zReserveAS",
    "Outlet Style Indicator": "zReserveBY",
    "Color Group": "zReserveAW",
    "Color Type": "Delivery",
    "Retailer Style #": "zReserveBB",
    "Local WHSL": "Local WHSL",
    "Transfer Price": "zReserveCB",
    "Size Range": "Size Scale",
    "Class Level 3": "zReserveAA",
    "Year": "Year",
    "Geography": "Geography",
    "Local MSRP": "Local MSRP"
}

DEFINED_ATTR_NAMES = DEFINED_ATTR_NAMES_EF

EP_SIZEINFO_HEADERS = [
DEFINED_ATTR_NAMES['Size Name'], DEFINED_ATTR_NAMES['Size Code']
]

EP_UPC_HEADERS = [
DEFINED_ATTR_NAMES['Color Desc'], DEFINED_ATTR_NAMES['Color Code'], DEFINED_ATTR_NAMES['Size Name'], DEFINED_ATTR_NAMES['Size Code'], 'UPC', DEFINED_ATTR_NAMES['Article #'], 'Last modified', 'Modified by'
]


